### ISSUE TITLE
TeX required?

### ISSUE THREAD

**Issue by eamcvey** [yihui/bookdown-minimal#1]
I cloned this minimal example and tried to build the book in RStudio IDE - following the instructions in the getting started section of the bookdown book.  I got an error about _main.tex which I assume was due to me not having TeX installed.  I deleted the tex file and the pdf_book default and then could successfully build the html version.  My suggestion is that, if I'm correct about the TeX cause of error here, that it be clearer either from the package or the bookdown book that TeX is required to be installed -- or better yet provide an option of the minimal example that's just html to make it _even easier_ for people to get started with the first example.

**Comment by yihui** [comment]
Good suggestion. I have commented out the pdf format. Thanks!
