### ISSUE TITLE
Delete the title A Minimal Book Example

### ISSUE THREAD

**Issue by itsmecevi** [yihui/bookdown-minimal#2]
Hallo @yihui . I write my thesis this semester. How can I delete the title A Minimal Book Example in my bookdown? Please find the picture attached. Thank you
![bookdown1](https://user-images.githubusercontent.com/27078712/52472386-77b44300-2b93-11e9-9ef8-7fd344789ad9.PNG)

**Comment by dullhunk** [comment]
Hello @itsmecevi the text "a minimal book example" comes from the _output.yaml file.  

You can replace it by editing the file, it took me a while to work that one out myself @yihui

**Comment by yihui** [comment]
@dullhunk Sorry about that. As a general solution, you may search for the text in the whole project when you are curious where a certain piece of text comes from (e.g., in RStudio: `Edit -> Find in Files`; <kbd>Cmd/Ctrl + Shift + F</kbd>).
